apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ecommerce-app.fullname" . }}-config
  labels:
    {{- include "ecommerce-app.labels" . | nindent 4 }}
data:
  # Basic configuration - connection strings are provided via environment variables
  app.name: {{ .Values.config.app.name | quote }}
  app.version: {{ .Values.config.app.version | quote }}
  app.environment: {{ .Values.config.app.environment | quote }}

  # CORS origins
  cors.origins: |
    http://{{ include "ecommerce-app.fullname" . }}-frontend:3000
    http://localhost:3000