{{- if false }}
# Legacy PVC for SQLite - disabled since we're using SQL Server
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "ecommerce-app.fullname" . }}-data
  labels:
    {{- include "ecommerce-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  accessModes:
    - {{ .Values.database.persistence.accessMode }}
  storageClassName: {{ .Values.database.persistence.storageClass }}
  resources:
    requests:
      storage: {{ .Values.database.persistence.size }}
{{- end }}