apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ecommerce-app.fullname" . }}-secret
  labels:
    {{- include "ecommerce-app.labels" . | nindent 4 }}
type: Opaque
stringData:
  jwt-secret: {{ .Values.config.jwt.secretKey | quote }}
  rabbitmq-password: {{ .Values.rabbitmq.auth.password | quote }}
  redis-password: {{ .Values.redis.auth.password | default "" | quote }}
  sqlserver-password: {{ .Values.config.sqlserver.password | quote }}