apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ecommerce-app.fullname" . }}-secret
  labels:
    {{- include "ecommerce-app.labels" . | nindent 4 }}
type: Opaque
stringData:
  jwt-secret: {{ .Values.backend.jwt.secretKey | quote }}
  rabbitmq-password: {{ .Values.rabbitmq.password | quote }}
  redis-password: {{ .Values.redis.password | quote }}