{{- if .Values.sqlserver.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ecommerce-app.fullname" . }}-sqlserver
  labels:
    {{- include "ecommerce-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: sqlserver
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "ecommerce-app.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: sqlserver
  template:
    metadata:
      labels:
        {{- include "ecommerce-app.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: sqlserver
    spec:
      containers:
        - name: sqlserver
          image: "{{ .Values.sqlserver.image.repository }}:{{ .Values.sqlserver.image.tag }}"
          imagePullPolicy: {{ .Values.sqlserver.image.pullPolicy }}
          ports:
            - name: sqlserver
              containerPort: 1433
              protocol: TCP
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "ecommerce-app.fullname" . }}-secret
                  key: sqlserver-password
            - name: MSSQL_PID
              value: "Express"
          resources:
            {{- toYaml .Values.sqlserver.resources | nindent 12 }}
          volumeMounts:
            - name: sqlserver-data
              mountPath: /var/opt/mssql
          livenessProbe:
            exec:
              command:
                - /opt/mssql-tools/bin/sqlcmd
                - -S
                - localhost
                - -U
                - sa
                - -P
                - $(SA_PASSWORD)
                - -Q
                - "SELECT 1"
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
          readinessProbe:
            exec:
              command:
                - /opt/mssql-tools/bin/sqlcmd
                - -S
                - localhost
                - -U
                - sa
                - -P
                - $(SA_PASSWORD)
                - -Q
                - "SELECT 1"
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
      volumes:
        {{- if .Values.sqlserver.persistence.enabled }}
        - name: sqlserver-data
          persistentVolumeClaim:
            claimName: {{ include "ecommerce-app.fullname" . }}-sqlserver-data
        {{- else }}
        - name: sqlserver-data
          emptyDir: {}
        {{- end }}
      {{- with .Values.sqlserver.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.sqlserver.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.sqlserver.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
