version: '3.8'

services:
  # Product Service
  product-service:
    build: ./ProductService
    container_name: product-service
    ports:
      - "5001:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=ProductsDb;User=sa;Password=Pass@word123;TrustServerCertificate=true
    depends_on:
      - sqlserver
    networks:
      - ecommerce-network

  # Order Service
  order-service:
    build: ./OrderService
    container_name: order-service
    ports:
      - "5002:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=OrdersDb;User=sa;Password=Pass@word123;TrustServerCertificate=true
      - Services__ProductService=http://product-service
    depends_on:
      - sqlserver
      - product-service
    networks:
      - ecommerce-network

  # SQL Server
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    ports:
      - "1433:1433"
    environment:
      - SA_PASSWORD=Pass@word123
      - ACCEPT_EULA=Y
    volumes:
      - sqlserver-data:/var/opt/mssql
    networks:
      - ecommerce-network

volumes:
  sqlserver-data:

networks:
  ecommerce-network:
    driver: bridge