apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    meta.helm.sh/release-name: simple-microservices
    meta.helm.sh/release-namespace: microservices-demo
  creationTimestamp: "2025-06-11T16:47:44Z"
  generation: 1
  labels:
    app: payment-service
    app.kubernetes.io/managed-by: Helm
    service: payment
  name: payment-service
  namespace: microservices-demo
  resourceVersion: "1399"
  uid: 33d4ce8b-9399-4638-b10c-4e67b65654f3
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: payment-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: payment-service
        service: payment
    spec:
      containers:
      - image: nginx:alpine
        imagePullPolicy: IfNotPresent
        name: payment-service
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: html
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: payment-service-html
        name: html
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-06-11T16:47:52Z"
    lastUpdateTime: "2025-06-11T16:47:52Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-06-11T16:47:44Z"
    lastUpdateTime: "2025-06-11T16:47:52Z"
    message: ReplicaSet "payment-service-6d7c954b58" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
