# Kind cluster configuration for E-Commerce Platform
# This creates a multi-node cluster suitable for microservices deployment

kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: ecommerce

# Cluster-wide configuration
networking:
  # Disable default CNI to use Calico (optional)
  disableDefaultCNI: false
  # Pod subnet
  podSubnet: "10.244.0.0/16"
  # Service subnet  
  serviceSubnet: "10.96.0.0/16"
  # API server port
  apiServerPort: 6443

# Node configuration
nodes:
  # Control plane node
  - role: control-plane
    image: kindest/node:v1.29.0
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
    extraPortMappings:
      # Frontend port mapping
      - containerPort: 30000
        hostPort: 3000
        protocol: TCP
      # Backend API port mapping  
      - containerPort: 30001
        hostPort: 5050
        protocol: TCP
      # Redis port mapping
      - containerPort: 30002
        hostPort: 6379
        protocol: TCP
      # RabbitMQ Management UI
      - containerPort: 30003
        hostPort: 15672
        protocol: TCP
      # RabbitMQ AMQP
      - containerPort: 30004
        hostPort: 5672
        protocol: TCP
      # Ingress controller ports
      - containerPort: 80
        hostPort: 80
        protocol: TCP
      - containerPort: 443
        hostPort: 443
        protocol: TCP

  # Worker node 1 - for application workloads
  - role: worker
    image: kindest/node:v1.29.0
    labels:
      workload-type: "application"
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "workload-type=application"

  # Worker node 2 - for data services
  - role: worker
    image: kindest/node:v1.29.0
    labels:
      workload-type: "data"
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "workload-type=data"

# Feature gates (optional)
featureGates:
  # Enable useful features
  "EphemeralContainers": true
  "PodSecurity": true
