apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ecommerce-apps

commonLabels:
  app.kubernetes.io/part-of: ecommerce
  app.kubernetes.io/managed-by: kustomize

resources:
  # ConfigMaps and Secrets
  - configmap.yaml
  
  # Services
  - product-catalog/deployment.yaml
  - product-catalog/service.yaml
  - product-catalog/configmap.yaml
  
  - order-management/deployment.yaml
  - order-management/service.yaml
  - order-management/configmap.yaml
  
  - user-management/deployment.yaml
  - user-management/service.yaml
  - user-management/configmap.yaml
  
  - notification-service/deployment.yaml
  - notification-service/service.yaml
  - notification-service/configmap.yaml
  
  - api-gateway/deployment.yaml
  - api-gateway/service.yaml
  - api-gateway/configmap.yaml
  
  # Ingress
  - ingress.yaml
  
  # Network Policies
  - network-policies.yaml

# Common environment variables for all services
configMapGenerator:
  - name: common-config
    literals:
      - ASPNETCORE_ENVIRONMENT=Production
      - AZURE_CLIENT_ID=managed-identity

# Secret generator (will be replaced by Azure Key Vault in production)
secretGenerator:
  - name: common-secrets
    literals:
      - DB_CONNECTION=will-be-replaced-by-keyvault

# Common patches
patches:
  - target:
      kind: Deployment
      labelSelector: "app.kubernetes.io/part-of=ecommerce"
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/livenessProbe
        value:
          httpGet:
            path: /health/live
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
      - op: add
        path: /spec/template/spec/containers/0/readinessProbe
        value:
          httpGet:
            path: /health/ready
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3

# Images
images:
  - name: product-catalog
    newName: ${ACR_LOGIN_SERVER}/product-catalog
    newTag: ${IMAGE_TAG}
  - name: order-management
    newName: ${ACR_LOGIN_SERVER}/order-management
    newTag: ${IMAGE_TAG}
  - name: user-management
    newName: ${ACR_LOGIN_SERVER}/user-management
    newTag: ${IMAGE_TAG}
  - name: notification-service
    newName: ${ACR_LOGIN_SERVER}/notification-service
    newTag: ${IMAGE_TAG}
  - name: api-gateway
    newName: ${ACR_LOGIN_SERVER}/api-gateway
    newTag: ${IMAGE_TAG}