apiVersion: v2
name: ecommerce-app
description: A comprehensive e-commerce platform with Next.js frontend and .NET 8 backend
type: application
version: 1.0.0
appVersion: "1.0.0"

keywords:
  - ecommerce
  - nextjs
  - dotnet
  - microservices
  - kubernetes

home: https://github.com/your-org/ecommerce-platform
sources:
  - https://github.com/your-org/ecommerce-platform

maintainers:
  - name: Development Team
    email: dev@ecommerce.com

dependencies:
  - name: redis
    version: "18.4.0"
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled
  - name: rabbitmq
    version: "12.5.0"
    repository: "https://charts.bitnami.com/bitnami"
    condition: rabbitmq.enabled
  - name: kube-prometheus-stack
    version: "55.5.0"
    repository: "https://prometheus-community.github.io/helm-charts"
    condition: monitoring.prometheus.enabled
  - name: grafana
    version: "7.0.19"
    repository: "https://grafana.github.io/helm-charts"
    condition: monitoring.grafana.enabled

annotations:
  category: E-Commerce
  licenses: MIT
