apiVersion: v1
kind: Service
metadata:
  name: {{ include "ecommerce-app.fullname" . }}-frontend
  labels:
    {{- include "ecommerce-app.labels" . | nindent 4 }}
    component: frontend
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "ecommerce-app.selectorLabels" . | nindent 4 }}
    component: frontend