apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  labels:
    app: api-gateway
    app.kubernetes.io/name: api-gateway
    app.kubernetes.io/component: gateway
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
        app.kubernetes.io/name: api-gateway
        app.kubernetes.io/component: gateway
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: api-gateway-sa
      nodeSelector:
        "nodepool-type": "user"
        "workload-type": "applications"
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - api-gateway
              topologyKey: kubernetes.io/hostname
      containers:
        - name: api-gateway
          image: api-gateway:latest
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
            - name: https
              containerPort: 443
              protocol: TCP
            - name: metrics
              containerPort: 9090
              protocol: TCP
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
            - name: ApplicationInsights__InstrumentationKey
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: AppInsightsKey
            - name: ReverseProxy__Clusters__products-cluster__Destinations__destination1__Address
              value: "http://product-catalog"
            - name: ReverseProxy__Clusters__orders-cluster__Destinations__destination1__Address
              value: "http://order-management"
            - name: ReverseProxy__Clusters__users-cluster__Destinations__destination1__Address
              value: "http://user-management"
            - name: ReverseProxy__Clusters__notifications-cluster__Destinations__destination1__Address
              value: "http://notification-service"
            - name: ASPNETCORE_URLS
              value: "http://+:80;https://+:443"
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 1Gi
          livenessProbe:
            httpGet:
              path: /health/live
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health/ready
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          volumeMounts:
            - name: config
              mountPath: /app/appsettings.Production.json
              subPath: appsettings.Production.json
              readOnly: true
            - name: secrets-store
              mountPath: /mnt/secrets-store
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: api-gateway-config
        - name: secrets-store
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: azure-keyvault-secrets
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-gateway-sa
  annotations:
    azure.workload.identity/client-id: ${AZURE_CLIENT_ID}