{{- if .Values.orderService.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  labels:
    app: order-service
    service: order
spec:
  replicas: {{ .Values.orderService.replicas }}
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
        service: order
    spec:
      containers:
      - name: order-service
        image: {{ .Values.orderService.image }}
        ports:
        - containerPort: {{ .Values.orderService.port }}
        volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html
        configMap:
          name: order-service-html
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  labels:
    app: order-service
spec:
  selector:
    app: order-service
  ports:
  - port: 80
    targetPort: {{ .Values.orderService.port }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: order-service-html
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head><title>Order Service</title></head>
    <body style="font-family: Arial; text-align: center; padding: 50px;">
      <h1>📦 Order Service</h1>
      <p>Port: 80 | Service: Orders</p>
      <div style="background: #e8f0ff; padding: 20px; margin: 20px; border-radius: 10px;">
        <h3>Recent Orders:</h3>
        <ul style="list-style: none;">
          <li>📱 Order #001 - iPhone (Pending)</li>
          <li>💻 Order #002 - MacBook (Shipped)</li>
          <li>⌚ Order #003 - Apple Watch (Delivered)</li>
        </ul>
      </div>
      <p><strong>Microservice #2</strong></p>
    </body>
    </html>
{{- end }}
