# Simplified Kind cluster configuration for E-Commerce Platform
# Single control-plane node with minimal configuration for better reliability

kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: ecommerce

# Cluster-wide configuration
networking:
  # Use default CNI (kindnet)
  disableDefaultCNI: false
  # Pod subnet
  podSubnet: "10.244.0.0/16"
  # Service subnet  
  serviceSubnet: "10.96.0.0/16"
  # API server port
  apiServerPort: 6443

# Single node configuration for simplicity
nodes:
  # Control plane node (also acts as worker)
  - role: control-plane
    image: kindest/node:v1.29.0
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
    extraPortMappings:
      # HTTP Ingress
      - containerPort: 80
        hostPort: 80
        protocol: TCP
      # HTTPS Ingress
      - containerPort: 443
        hostPort: 443
        protocol: TCP
      # Frontend port (for NodePort services)
      - containerPort: 30000
        hostPort: 5050
        protocol: TCP
      # Backend API port (for NodePort services)
      - containerPort: 30001
        hostPort: 5051
        protocol: TCP
